/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anaparastasi_project;

import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.io.File;
import static java.lang.reflect.Array.set;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.jena.rdf.model.*;

import org.apache.jena.ontology.*;

import org.apache.jena.util.iterator.ExtendedIterator;

import static org.apache.jena.ontology.OntModelSpec.OWL_MEM;
import static org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler.logger;
import static org.semanticweb.owlapi.apibinding.OWLFunctionalSyntaxFactory.IRI;
import org.semanticweb.owlapi.apibinding.OWLManager;
import static org.semanticweb.owlapi.krss1.parser.NameResolverStrategy.IRI;

import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;

/**
 *
 * @author Ρωμανός
 */
public class Owl_ontology extends javax.swing.JFrame {

    /**
     * Creates new form Owl_ontology
     */
    public Owl_ontology() {
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        class_ComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        subclass_ComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(220, 113, 7));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Please select one of the following options:");

        jButton1.setBackground(new java.awt.Color(17, 91, 238));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Retrieve instances");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(17, 91, 238));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Insert instances");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(17, 91, 238));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Run SPARQL query");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(17, 91, 238));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Search for instances");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel2.setText("Welcome to FootbOWL!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        MainPanel.add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(220, 113, 7));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Please select one class:");

        class_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        class_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                class_ComboBoxItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Please select one subclass:");

        subclass_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        subclass_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subclass_ComboBoxItemStateChanged(evt);
            }
        });
        subclass_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subclass_ComboBoxActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instances"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(class_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(subclass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(class_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(subclass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel4.setVisible(false);
        subclass_ComboBox.setVisible(false);

        MainPanel.add(jPanel2, "card3");

        jPanel3.setBackground(new java.awt.Color(220, 113, 7));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel9.setText("Instance insertion");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Select class:");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Select subclass:");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Add instance:");

        jButton5.setBackground(new java.awt.Color(17, 91, 238));
        jButton5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Submit");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox3, 0, 71, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        MainPanel.add(jPanel3, "card4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        MainPanel.add(jPanel4, "card5");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        MainPanel.add(jPanel5, "card6");

        jPanel6.setBackground(new java.awt.Color(221, 89, 1));

        jButton6.setBackground(new java.awt.Color(17, 91, 238));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addContainerGap())
        );

        jButton6.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "card6");
        jButton6.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "card5");
        jButton6.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "card3");

        jButton6.setVisible(true);
        InfModel inf1 = ModelFactory.createRDFSModel(model);
        ArrayList<String> class_array = new ArrayList<String>();
        String sth1 = model.getOntClass(base + "Game").getLocalName().toString();
        class_array.add(sth1);
        ExtendedIterator<OntClass> iter = model.listHierarchyRootClasses();

        while (iter.hasNext()) {
            OntClass essaClasse = (OntClass) iter.next();
            String vClasse = essaClasse.getLocalName();

            if (vClasse != null) {
                System.out.println(vClasse);
                class_array.add(vClasse);
            }
        }
        String[] items = new String[class_array.size()];
        class_array.toArray(items);

        class_ComboBox.setModel(new DefaultComboBoxModel<String>(items));


    }//GEN-LAST:event_jButton1ActionPerformed
    

    private void class_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_class_ComboBoxItemStateChanged
        // TODO add your handling code here:
        flag = false;
        jLabel4.setVisible(false);
        subclass_ComboBox.setVisible(false);
        
        String selected_class = class_ComboBox.getSelectedItem().toString();
        OntClass foot = model.getOntClass(base + selected_class);
        ArrayList<String> subclass_array = new ArrayList<String>();
        DefaultTableModel table_model = (DefaultTableModel) jTable3.getModel();
        table_model.setRowCount(0);
        ExtendedIterator instances = foot.listInstances();

        while (instances.hasNext()) {
            Individual thisInstance = (Individual) instances.next();
            String individual = thisInstance.getLocalName().toString();
            System.out.println("  Found instance: " + thisInstance.toString());
            if(table_model.getRowCount()==0){              
              table_model.addRow(new Object[]{individual});
            }
            for (int i = 0; i < table_model.getRowCount(); i++) {
                
                String obj = table_model.getValueAt(i, 0).toString();
                if(obj.equals(individual)){
                 break;
                }
                if(i == table_model.getRowCount()-1){
                    System.out.println("obj");
                    System.out.println(obj);
                    System.out.println("individual");
                    System.out.println(individual);
                  table_model.addRow(new Object[]{individual});
                 
                }
                
            }
             
        }

        for (Iterator<OntClass> i = foot.listSubClasses(); i.hasNext();) {
            String c = i.next().getLocalName().toString();
            if (c != null) {
                flag = true;
                OntClass football = model.getOntClass(base + c);
                for (Iterator<OntClass> j = football.listSubClasses(); j.hasNext();) {
                    String b = j.next().getLocalName().toString();
                    subclass_array.add(b);
                    System.out.println(b);
                    OntClass sub2 = model.getOntClass(base + b);
                    for (Iterator<OntClass> k = sub2.listSubClasses(); k.hasNext();) {
                        String a = k.next().getLocalName().toString();
                        subclass_array.add(a);
                        System.out.println(a);
                        OntClass sub3 = model.getOntClass(base + a);
                        for (Iterator<OntClass> l = sub3.listSubClasses(); l.hasNext();) {
                            String d = l.next().getLocalName().toString();
                            subclass_array.add(d);
                            System.out.println(d);

                        }
                    }
                }

                System.out.println(c);
                subclass_array.add(c);
            }
        }
        if (flag) {
            jLabel4.setVisible(true);
            subclass_ComboBox.setVisible(true);
        }
        String[] items = new String[subclass_array.size()];
        subclass_array.toArray(items);

        subclass_ComboBox.setModel(new DefaultComboBoxModel<String>(items));
    }//GEN-LAST:event_class_ComboBoxItemStateChanged

    private void subclass_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subclass_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subclass_ComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "card4");
        jButton6.setVisible(true);
     
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    private void subclass_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subclass_ComboBoxItemStateChanged
        // TODO add your handling code here:
        String selected_subclass = subclass_ComboBox.getSelectedItem().toString();
        DefaultTableModel table_model = (DefaultTableModel) jTable3.getModel();
        table_model.setRowCount(0);
        OntClass foot = model.getOntClass(base + selected_subclass);
        ExtendedIterator instances = foot.listInstances();

        while (instances.hasNext()) {
            Individual thisInstance = (Individual) instances.next();
            String individual = thisInstance.getLocalName().toString();
            System.out.println("  Found instance: " + thisInstance.toString());
            if(table_model.getRowCount()==0){
                table_model.addRow(new Object[]{individual});
            }
            for (int i = 0; i < table_model.getRowCount(); i++) {

                String obj = table_model.getValueAt(i, 0).toString();
                if(obj.equals(individual)){
                    break;
                }
                if(i == table_model.getRowCount()-1){

                    System.out.println(obj);
                    System.out.println(individual);
                    table_model.addRow(new Object[]{individual});

                }

            }

        }
    }//GEN-LAST:event_subclass_ComboBoxItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "card2");
        jButton6.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
    private final static String PANEL3 = "panel 3";
    private final static String PANEL1 = "panel 1";
    private final static String PANEL2 = "panel 2";
    private final static String PANEL4 = "panel 4";

    protected JPanel initFields() {
        JPanel panel1_1 = new JPanel();
        return panel1_1;
    }
//user

    public void myInitComponents() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //load file and create model
            model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM);
            model.read("footBALL.owl", null);
            base = "http://www.semanticweb.org/ρωμανός/ontologies/2020/11/untitled-ontology-8#";

            //create inference model
            //InfModel inf = ModelFactory.createRDFSModel(model); 
            // OntModel new_base = ModelFactory.createOntologyModel( OWL_MEM );
            OntClass foot = model.getOntClass(base + "Competition");
            ExtendedIterator classes = model.listClasses();
            String sth = model.listHierarchyRootClasses().toString();
            System.out.println(sth);

//        for (ExtendedIterator<OntClass> i =  new_base.listHierarchyRootClasses(); i.hasNext();) {
//            OntClass ontClass = i.next();
//            System.out.println(ontClass);
//            //logger.debug("Base class = " + ontClass);
//        }
//        ExtendedIterator instances = foot.listSubClasses();
//		      while (instances.hasNext()){
//		        Individual thisInstance = (Individual) instances.next();
//		        System.out.println("  Found instance: " + thisInstance.toString());
//		      }
//            System.out.println(classes);
//        while (classes.hasNext()) {
//                OntClass essaClasse = (OntClass) classes.next();
//
//                String vClasse = essaClasse.getLocalName().toString();
//
//                if (essaClasse.hasSubClass()) {
//                    System.out.println("Class: " + vClasse);
//                    OntClass cla = model.getOntClass(base + vClasse);
//                    for (Iterator i = cla.listSubClasses(); i.hasNext();) {
//                        OntClass c = (OntClass) i.next();
//                        System.out.print("   " + c.getLocalName() + " " + "\n");
//                    }
//                }
//            }
//        for (Iterator<OntClass> i = foot.listSubClasses(); i.hasNext(); ) {
//			  OntClass c = i.next();
//			  if (c.getURI() != null)
//			  System.out.println( c.getURI() );
//			}
            ExtendedIterator<OntClass> iter = model.listHierarchyRootClasses();

            while (iter.hasNext()) {
                OntClass essaClasse = (OntClass) iter.next();
                String vClasse = essaClasse.getLocalName();
                if (vClasse != null) {
                    System.out.println(vClasse);
                }
                //System.out.println(iter.next());
            }
//        
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

//       OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
//       File file = new File ("ex_foot.owl");
//       OWLOntology ont = manager.loadOntologyFromOntologyDocument(IRI.create(file));
//       //OWLOntology ontology = manager.loadOntology(IRI.create(iri));
//       OWLDataFactory owlDF = manager.getOWLDataFactory();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owl_ontology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owl_ontology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owl_ontology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owl_ontology.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owl_ontology().setVisible(true);
            }
        });
    }
    protected static String base;
    protected static OntModel model;
    protected boolean flag;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox<String> class_ComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> subclass_ComboBox;
    // End of variables declaration//GEN-END:variables
}
