PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX uni: <http://www.mydomain.com/uni-ns/>

SELECT ?name
WHERE {	?x	uni:member_of ?dep.	
        ?x 	uni:has_name ?name.			
		?dep	uni:dep_city "Patras".
}